-- Restore resource center tools from the original production data snapshot.
-- Uses ON CONFLICT (id) on the PRIMARY KEY which is always safe.

INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (1, 'Y1', 'ICP Scorecard', 'Score any deal across 5 ICP dimensions. Advance or disqualify based on data, not gut.', 'yellow', 'https://docs.google.com/spreadsheets/d/1FwDJz-dp8Jviu0kh4S5OEX-Z2sA_iVQd', true, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (8, 'G1', 'Key Stakeholder Mapping Tool', 'Map every buying committee member across 6 roles. Identify gaps and multi-threading targets.', 'green', 'https://docs.google.com/spreadsheets/d/1f3wYz58wquVVTozztsrtpubQz3-nO__S', true, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (16, 'R1', 'Obstacle Forecast Play', 'Ask: what steps are left and who or what could slow this down? Run before any close push.', 'red', 'https://docs.google.com/spreadsheets/d/1hO-KtJ56ryRilmXFAVaot0ji-m_hOvMA', true, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (23, 'B1', 'Two-Minute Drill Worksheet', 'Execute under pressure. The final-drive framework for deals in the last stretch.', 'bonus', 'https://docs.google.com/spreadsheets/d/1OYFmQfdwEHewf_eEKbuOPpvVp-RzF1x7', true, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (2, 'Y2', 'Priority Fit Play', 'Test if this initiative is a must-solve now or a nice-to-have someday.', 'yellow', 'https://docs.google.com/spreadsheets/d/1-cIeGdmK750313QeJ7vR-4ac6MUy-j3l', true, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (9, 'G2', 'Multi-Threading Like a Pro', 'Outreach templates for engaging new stakeholders through your champion or directly.', 'green', 'https://docs.google.com/spreadsheets/d/1BqsgPkOO-3B90zMU5-CypvzCRiwTSuj8', true, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (17, 'R2', 'Closing Triangulation Play', 'Confirm alignment across all 5 stakeholder categories before the close.', 'red', 'https://docs.google.com/spreadsheets/d/1r2iHN2hK1f-_8ypTDy4lJ--1iU4WK2v3', true, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (24, 'B2', 'The Hail Mary Offer', 'Last-resort play for stalled or cold deals. Use with discipline.', 'bonus', 'https://docs.google.com/document/d/1GHHIu-kGvVxhQupGgtsgypcYlZsPcyEn', true, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (3, 'Y3', '4F Deal Filter', 'Apply the Fit / Friction / Funding / Forecast scoring framework to any deal.', 'yellow', 'https://docs.google.com/spreadsheets/d/1B5kDCZqscpfhvJIz-k6JUZbVXP-JryGA', true, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (10, 'G3', 'Friction Preload Play', 'Create urgency before entering the Red Zone. Surface the cost of delay.', 'green', 'https://docs.google.com/spreadsheets/d/16pbIvNIF8iIiGUl_mWNys94pWvIkCEkQ', true, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (18, 'R3', 'Final Objection Sweep Play', 'Surface every unspoken concern 1-2 weeks before close.', 'red', 'https://docs.google.com/spreadsheets/d/1BaI8qua24XWM1Rq8jVt4upe-Tboa4pUG', true, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (25, 'B3', 'Enterprise Sales Playbook Template', 'The complete zone-mapped playbook framework. Customize for your team.', 'bonus', 'https://docs.google.com/spreadsheets/d/1Etkk29-AW_B2f-quoy57ZkcofYC6ZsYN', true, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (4, 'Y4', 'Deep Pain Probe', 'Run the 3-part discovery sequence: problem, business impact, personal stakes.', 'yellow', 'https://docs.google.com/spreadsheets/d/12-acmcB_ibCS-Wbtn3PVdrIazqLxu9K6', true, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (11, 'G4', 'Pipeline Velocity Tracker', 'Track deal progress through zones. Spot stalls before they kill your quarter.', 'green', 'https://docs.google.com/spreadsheets/d/1pBQF8T-V5v-Qox6ZXqfJZU8sEVBCVYjZ', true, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (19, 'R4', 'Negotiation Prep Sheet', 'Map your concessions, walk-away points, and trade plays before the negotiation starts.', 'red', 'https://docs.google.com/spreadsheets/d/1eIMDhXKXk-kvujDFl3Y7b3n8jGe5Vhx7', true, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (26, 'B4', 'Cold-to-Close Sequence Builder', 'Build a full outreach sequence from cold outreach through close. Zone by zone.', 'bonus', 'https://docs.google.com/spreadsheets/d/1S_H--Fqp7vM8EToA7mBLJ7JTJEf0WMHM', true, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (5, 'Y5', 'Decision Timeline Mapper', 'Map the buyer''s decision timeline and identify key milestones before the close window closes.', 'yellow', 'https://docs.google.com/spreadsheets/d/1L4INYrQpYa8yH7j3AYCM_Fxe6FyUJhKL', true, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (12, 'G5', 'Objection Playbook', '22 objection responses mapped to zone. Handle any pushback with confidence.', 'green', 'https://docs.google.com/spreadsheets/d/1HCgE_L6_QxB0OZ9-KAgtDR0vPM4EFU7y', true, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (20, 'R5', 'Contract Acceleration Play', 'Remove legal and procurement friction before they stall your close.', 'red', 'https://docs.google.com/spreadsheets/d/1kRELUYx0PN5h7tM-dK6I0XJIM91HXl-g', true, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (27, 'B5', 'RZS Play Catalog — All 64 Plays', 'The complete play library from the book. Every play, every zone.', 'bonus', 'https://docs.google.com/spreadsheets/d/1AuKmO6Tpz_e6t5Z2RNSGY1H-Ze8RdzTi', true, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (6, 'Y6', 'Pressure-Test Close', 'Separate real buying intent from polite interest.', 'yellow', 'https://docs.google.com/spreadsheets/d/1MLWjKU1n5lKX3N78WKhvyFXZiwbzbSJ0', true, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (13, 'G6', 'Champion Activation Playbook', 'Scripts and tools for activating your champion as an internal seller.', 'green', 'https://docs.google.com/spreadsheets/d/1UmUNbPVhW2mqPWh3MvNxwo_sUoGzXnTa', true, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (21, 'R6', 'Executive Briefing Builder', 'A structured tool for high-impact executive briefings in Red Zone deals.', 'red', 'https://docs.google.com/document/d/1ZbWtgvpugUdfLm2Y4BBg9jiGsqW-SyoV', true, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (28, 'B6', 'RZS Chapter Drills', 'Practice exercises mapped to every chapter. Solo or team drills by zone.', 'bonus', 'https://docs.google.com/document/d/1hgqhZ45BXGkmj1VwpG5XXFsGAIpBV1Fw', true, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (7, 'Y7', 'Kill-with-Confidence Script', 'Walk away from bad-fit deals without burning bridges.', 'yellow', 'https://docs.google.com/spreadsheets/d/1bKv2QkqlkgIFwLnqLUktFN-qGaK_PTvh', true, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (14, 'G7', 'Mutual Action Plan', 'Co-create a shared close plan with your champion. Dates, owners, milestones.', 'green', 'https://docs.google.com/spreadsheets/d/17pYHyFkONyiJ_D14-_RX2VZaRNLyRMWS', true, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (22, 'R7', 'Own the Close™ Scorecard', 'The flagship Red Zone tool. Score your deal across 8 closing dimensions.', 'red', 'https://drive.google.com/file/d/1_YVZNkPZjli19HOpMhKdDF5B1MQkNMAu', true, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (29, 'B7', 'Cost of Inaction Calculator', 'Quantify the business cost of delay. Built for urgency creation conversations.', 'bonus', 'https://docs.google.com/spreadsheets/d/1qD_4rd6UmWOTCTzn7CAafGeRog6wYCUY', true, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (15, 'G8', 'Executive Briefing Builder', 'Prepare and deliver a high-impact executive briefing at any stage.', 'green', 'https://docs.google.com/document/d/1ZbWtgvpugUdfLm2Y4BBg9jiGsqW-SyoV', true, 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource_center_tools (id, code, name, description, zone, url, is_active, sort_order) VALUES (30, 'B8', 'Enterprise Account Planning', 'Build a strategic account plan for any ICP-fit prospect before the first meeting.', 'bonus', 'https://docs.google.com/spreadsheets/d/1WrKGWT-bzgKang9kiPL_Mhhk7hKUJQgS', true, 8) ON CONFLICT (id) DO NOTHING;

SELECT setval('resource_center_tools_id_seq', (SELECT MAX(id) FROM resource_center_tools));
